### ISSUE TITLE
Additional help needed for setup

### ISSUE THREAD

**Issue by aceisace** [sidddy/flora#11]
Hi, I've been trying to set this scipt up on Arduino IDE according to your instructions. It seems as though something is missing: 

`BLEDevice.h: No such file or directory`

Is there any additional step or library/libraries required for Arduino IDE? If yes, could you add the url of the library in the README?

I'm using a ESP32-WROOM-32 on my Board. 
Thanks in advance

**Comment by sidddy** [comment]
closing due to lack of feedback
