### ISSUE TITLE
Sketch Size

### ISSUE THREAD

**Issue by domebe** [sidddy/flora#3]
Hey there, thanks for everything so far...

I still just don't get the changing partition table size.
All i found is the make menuconfig, but there is no menuconfig file at all...

Maybe you could help out.

Thanks alot

**Comment by sidddy** [comment]
Hi,

you have to use a non-standard partition layout and change the max build size in the boards.txt file.
E.g. you could follow the steps described at
https://desire.giesecke.tk/index.php/2018/04/20/change-partition-size-arduino-ide/

(referenced by bern6666 in #2)

Let me know if that works for you.

sidddy

**Comment by sidddy** [comment]
closing due to lack of feedback
