### ISSUE TITLE
No output, except "user code done"

### ISSUE THREAD

**Issue by oetti77** [sidddy/flora#4]
Hi,

i 've changed the partition size, compiled the sketch and uploaded it successfully, but there is nothing more than "user code done" in the serial monitor. 

Any hints are appreciated, how to fix this.

Chris

**Comment by oetti77** [comment]
I switched to PlatformIO. Everything is fine now.

Chris

**Comment by sidddy** [comment]
Hi Chris,

alright, thanks for the update!
I'll close this issue in that case.

BR
sidddy
