### ISSUE TITLE
Add Support for "Xiaomi Mijia Bluetooth Temperature Humidity Sensor"

### ISSUE THREAD

**Issue by aHVzY2g** [sidddy/flora#6]
High would it be possible to add support for the "Xiaomi Mijia Bluetooth Temperature Humidity Sensor".

Which information would you need?

I found this project which also contains data about the sensor protocol:
https://github.com/mspider65/Xiaomi-Mijia-Bluetooth-Temperature-and-Humidity-Sensor

**Comment by sidddy** [comment]
Hi,

communicationg with an ESP32 to an Xiaomi Mijia should be theoreticall possible, but I will not add support for Xiaomi Mijia sensors in flora for two reasons:
1) The communication protocol is different from the one used for Flora sensors, therefore I would basically need to maintain two different code bases
2) I do not own such sensor and therefore debugging etc would be a very time-consuming activity...

Implementing a new sketch for Xiaomi Mijia should be rather simple though, inspired by Flora and the protocol description you referred to.
